; huffman codes for characters

; 4-bit chars
%xdefine __ 0
%xdefine _r 1
%xdefine _t 2
%xdefine _o 3
%xdefine _e 4
%xdefine _a 5
%xdefine _n 6
%xdefine _i 7

; 5-bit chars
%xdefine _s 0x10
%xdefine _m 0x11
%xdefine _c 0x12
%xdefine _y 0x13
%xdefine _l 0x14
%xdefine _g 0x15
%xdefine _f 0x16
%xdefine _w 0x17

; 7-bit chars
%xdefine _d 0x60
%xdefine _v 0x61
%xdefine _p 0x62
%xdefine _b 0x63
%xdefine _h 0x64
%xdefine _x 0x65
%xdefine _u 0x66
%xdefine _q 0x67

%xdefine _0 0x68
%xdefine _1 0x69
%xdefine _2 0x6A
%xdefine _3 0x6B
%xdefine _4 0x6C
%xdefine _5 0x6D
%xdefine _6 0x6E
%xdefine _7 0x6F

%xdefine _8 0x70
%xdefine _9 0x71
%xdefine _j 0x72
%xdefine _dash 0x73
%xdefine _k 0x74
%xdefine _dot 0x75
%xdefine _z 0x76
%xdefine _slash 0x77

%xdefine _semi  0x78
%xdefine _colon 0x79
%xdefine _store 0x7A
%xdefine _plus 0x7B
%xdefine _fetch 0x7C
%xdefine _times 0x7D
%xdefine _comma 0x7E
%xdefine _question 0x7F
