BLOCK 26
FORTH "[TEXTCAPITALIZED]", "compiled",  "[TEXT]", "macros",  "[EXECUTE]", "forth"
FORTH "block",  "[TEXT]", "n-n",  "[COMPILESHORTHEX]", "100",  "*", off, +, ";"
FORTH "r@",  "[TEXT]", "-n",  "r@",  ";"
FORTH "@",  "[TEXT]", "a-n",  "@",  ";"
FORTH "!",  "[TEXT]", "an-",  "!",  ";"
FORTH "+",  "[TEXT]", "nn-n",  "+",  ";"
FORTH "invert",  "[TEXT]", "n-n",  "invert",  ";"
FORTH "*/",  "[TEXT]", "nnn-n",  "*/",  ";"
FORTH "*",  "[TEXT]", "nn-n",  "*",  ";"
FORTH "/",  "[TEXT]", "nn-n",  "/",  ";"
FORTH "2*",  "[TEXT]", "n-n",  "2*",  ";"
FORTH "2/",  "[TEXT]", "n-n",  "2/",  ";"
FORTH "dup",  "[TEXT]", "n-nn",  "dup",  ";"
FORTH "swap",  "[TEXT]", "nn-nn",  "swap",  ";",  "[TEXTCAPITALIZED]", "arithmetic"
FORTH "negate",  "[TEXT]", "n-n",  "invert",  "[COMPILESHORT]", "1",  "+",  ";"
FORTH "-",  "[TEXT]", "nn-n",  "negate",  "+",  ";"
FORTH "min",  "[TEXT]", "nn-n",  "less",  "if",  "drop",  ";",  "then",  "swap",  "drop",  ";"
FORTH "abs",  "[TEXT]", "n-u",  "dup",  "negate"
FORTH "max",  "[TEXT]", "nn-n",  "less",  "if",  "swap",  "then",  "drop",  ";"
FORTH "v+",  "[TEXT]", "vv-v",  "push",  "u+",  "pop",  "+",  ";"
FORTH "writes",  "[TEXT]", "acn",  "cli",  "for",  "write",  "next",  "drop",  "drop",  ";"
FORTH "reads",  "[TEXT]", "acn",  "cli",  "for",  "read",  "next",  "drop",  "drop",  ";"
FORTH "h",  "[TEXT]", "-a",  "sp",  "[EXECUTESHORT]", "20",  "+",  ";"
FORTH "save",  "empt",  "[COMPILESHORT]", "0",  "dup",  "[EXECUTE]", "nc",  "@",  "writes",  "/flop",  ";"
BLOCK
