BLOCK 28
FORTH "[TEXTCAPITALIZED]", "relative",  "[TEXT]", "load",  "[TEXT]", "blocks"
FORTH "nload",  "r@",  "[COMPILESHORTHEX]", "100",  "/",  "[COMPILESHORT]", "2",  "+",  "load",  ";"
FORTH "+load",  "[TEXT]", "n-",  "r@",  "[COMPILESHORTHEX]", "100",  "/",  "+",  "load",  ";"
FORTH "blk",  "[TEXT]", "-a",  "[EXECUTESHORTHEX]", "a86",  ";"
FORTH "ll",  "blk",  "@",  "load",  ";"
FORTH "sect",  "blk",  "@",  "[COMPILESHORT]", "18",  "/",  "dup",  "[COMPILESHORT]", "18",  "*",  "block",  "swap",  ";"
FORTH "ss",  "sect",  "[COMPILESHORT]", "1",  "writes",  "/flop",  ";"
FORTH "uu",  "sect",  "[COMPILESHORT]", "1",  "reads",  "/flop",  ";",  "[VARIABLE]", "lblk", "[BINARY]", "44"
FORTH "ld",  "[TEXT]", "n-",  "dup",  "lblk",  "!",  "load",  ";"
FORTH "vv",  "lblk",  "@",  "edit",  ";"
FORTH "help",  "lblk",  "@",  "[COMPILESHORT]", "1",  "+",  "edit",  ";",  "[TEXTCAPITALIZED]", "real",  "[TEXTCAPITALIZED]", "time",  "[TEXTCAPITALIZED]", "clock",  "[VARIABLE]", "khz", "[BINARY]", "124fa9"
FORTH "rtc@",  "[TEXT]", "t-c",  "[COMPILESHORTHEX]", "70",  "p!",  "[COMPILESHORTHEX]", "71",  "p@",  ";"
FORTH "rtc!",  "[TEXT]", "ct-",  "[COMPILESHORTHEX]", "70",  "p!",  "[COMPILESHORTHEX]", "71",  "p!",  ";"
FORTH "hi",  "[COMPILESHORT]", "10",  "rtc@",  "[COMPILESHORTHEX]", "80",  "and",  "drop",  "0if",  "hi",  ";",  "then",  ";"
FORTH "lo",  "[COMPILESHORT]", "10",  "rtc@",  "[COMPILESHORTHEX]", "80",  "and",  "drop",  "if",  "lo",  ";",  "then",  ";"
FORTH "cal",  "hi",  "lo",  "time",  "invert",  "hi",  "lo",  "time",  "+",  "[COMPILESHORT]", "500",  "+",  "[COMPILESHORT]", "1000",  "/",  "khz",  "!",  ";"
FORTH "ms",  "[TEXT]", "n-",  "khz",  "@",  "*",  "time",  "+",  "begin",  "dup",  "time",  "invert",  "+",  "drop",  "-if",  "drop",  ";",  "then",  "end",  "drop",  ";"
FORTH "secs",  "[TEXT]", "n-",  "for",  "pause",  "lo",  "hi",  "next",  ";",  "[EXECUTE]", "macro"
FORTH "swapb",  "[TEXT]", "w-w",  "[COMPILESHORTHEX]", "e086",  "2,",  ";",  "[EXECUTE]", "forth"
FORTH "split",  "dup",  "swapb",  "[COMPILESHORTHEX]", "ff",  "and",  "swap",  "[COMPILESHORTHEX]", "ff",  "and",  ";"
BLOCK
