#!/bin/bash
gcc `sdl-config --cflags --libs` -o xcf main.c mem.s
as -o color.o color.s
if test -a color.o; then
cp color.com blocks
ld --oformat binary -Ttext `nm xcf | awk '/ xcf$/ {print "0x" $1}'` -o color.com color.o
dd if=blocks of=color.com bs=1024 seek=12 skip=12
rm blocks color.o
fi
